# Generated by Django 3.1 on 2020-12-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
