# Generated by Django 3.1 on 2020-12-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_orderline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_update',
            new_name='date_updated',
        ),
    ]
